// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oxscfneaecwjyumoezyh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im94c2NmbmVhZWN3anl1bW9lenloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjM2Mjg0NTAsImV4cCI6MjA3OTIwNDQ1MH0.266TbFlFMcmAn2cWGI-44RIikBX8msvmPs3j-xdR6lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});